UAndes.ICC5103.202301/Controllers/AdquirentesController.cs
using NUnit.Framework.Constraints;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Diagnostics;
using System.Linq;
using System.Net;
using System.Runtime.Remoting.Messaging;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using System.Text.RegularExpressions;
using UAndes.ICC5103._202301.Models;

namespace UAndes.ICC5103._202301.Controllers
{
    public class AdquirentesController : Controller
    {
<<<<<<< Updated upstream
        private InscripcionesBrDbGrupo06Entities db = new InscripcionesBrDbGrupo06Entities();
=======
        private DateTime _2019 = new DateTime(2019, 1, 1);
        public InscripcionesBrDbGrupo06Entities db = new InscripcionesBrDbGrupo06Entities();

        
>>>>>>> Stashed changes

        // GET: Adquirentes
        public ActionResult Index()
        {
            var adquirenteSet = db.AdquirenteSet.Include(a => a.FormularioSet);
            return View(adquirenteSet.ToList());
        }

        // GET: Adquirentes/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AdquirenteSet adquirenteSet = db.AdquirenteSet.Find(id);
            if (adquirenteSet == null)
            {
                return HttpNotFound();
            }
            return View(adquirenteSet);
        }

        // GET: Adquirentes/Create 
        public ActionResult Create()
        {
            ViewBag.FormularioSetNumeroAtencion = new SelectList(db.FormularioSet, "NumeroAtencion", "CNE");
            return View();
        }

        // POST: Adquirentes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(int numeroAtencion, string rut, string porcentajeDerechos, string derechosNoAcreditados)
        {
            decimal porcentajeDerechosParse;
            bool derechosNoAcreditadosParse = false;
            //Se revisa si el input está en formato correcto, si no, no agrega al adquirente y recarga la página
            try
            {
                porcentajeDerechosParse = Decimal.Parse(porcentajeDerechos);
                if (derechosNoAcreditados == "on") { derechosNoAcreditadosParse = true; }
            }
            catch (FormatException) { return RedirectToAction("Edit", "Formularios", new { id = numeroAtencion });}

            if (!IsRUTValido(rut)) { return RedirectToAction("Edit", "Formularios", new { id = numeroAtencion }); }

            //Crea al adquirente
            AdquirenteSet adquirenteSet = new AdquirenteSet();
            adquirenteSet.FormularioSetNumeroAtencion = numeroAtencion;
            adquirenteSet.RUT = rut;
            if (derechosNoAcreditadosParse) {porcentajeDerechosParse = 0;adquirenteSet.PorcentajeDerechos = 0;}
            else if (porcentajeDerechosParse > 0 && porcentajeDerechosParse <= 100) {adquirenteSet.PorcentajeDerechos = porcentajeDerechosParse;}
            else { return RedirectToAction("Edit", "Formularios", new { id = numeroAtencion });}
            adquirenteSet.DerechosNoAcreditados = derechosNoAcreditadosParse;

            //Busca al formulario y revisa si el porcentaje disponible permite la creación de este adquirente
            FormularioSet formularioSet = db.FormularioSet.Find(numeroAtencion);
            if (porcentajeDerechosParse >= 0 && (formularioSet.PorcentajeDisponible - porcentajeDerechosParse >= 0))
            { formularioSet.PorcentajeDisponible -= porcentajeDerechosParse; }
            else { return RedirectToAction("Edit", "Formularios", new { id = numeroAtencion });}

            if (ModelState.IsValid)
            {
                db.Entry(formularioSet).State = EntityState.Added;
                db.AdquirenteSet.Add(adquirenteSet);
                db.SaveChanges();
            }
            return RedirectToAction("Edit", "Formularios", new { id = adquirenteSet.FormularioSetNumeroAtencion });
        }

        // GET: Adquirentes/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AdquirenteSet adquirenteSet = db.AdquirenteSet.Find(id);
            if (adquirenteSet == null)
            {
                return HttpNotFound();
            }
            ViewBag.FormularioSetNumeroAtencion = new SelectList(db.FormularioSet, "NumeroAtencion", "CNE", adquirenteSet.FormularioSetNumeroAtencion);
            return View(adquirenteSet);
        }

        // POST: Adquirentes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "RUT,PorcentajeDerechos,DerechosNoAcreditados,FormularioSetNumeroAtencion")] AdquirenteSet adquirenteSet)
        {
            if (ModelState.IsValid)
            {
                db.Entry(adquirenteSet).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.FormularioSetNumeroAtencion = new SelectList(db.FormularioSet, "NumeroAtencion", "CNE", adquirenteSet.FormularioSetNumeroAtencion);
            return View(adquirenteSet);
        }

        // GET: Adquirentes/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AdquirenteSet adquirenteSet = db.AdquirenteSet.Find(id);
            if (adquirenteSet == null)
            {
                return HttpNotFound();
            }
            return View(adquirenteSet);
        }

        // POST: Adquirentes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            AdquirenteSet adquirenteSet = db.AdquirenteSet.Find(id);
            db.AdquirenteSet.Remove(adquirenteSet);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private bool IsRUTValido(string rut)
        {
            string rutInput = rut;
            rutInput = rutInput.Replace(".","").ToUpper();

            //Expresion obtenida de https://gist.github.com/donpandix/045f865c3bf800893036
            Regex rutExpression = new Regex("^([0-9]+-[0-9K])$");
            if (!rutExpression.IsMatch(rutInput))
            {
                return false;
            }
            
            rutInput = rutInput.Replace("-","");

            List<string> rutCharsList = new List<string>();
            foreach (char digito in rutInput)
            {
                rutCharsList.Insert(0, digito.ToString());
            }
            string verificadorInput = rutCharsList[0];
            rutCharsList.RemoveAt(0);

            int multiplierRut = 2;
            int totalSumCharacters = 0;
            foreach (string digito in rutCharsList)
            {
                int digitoInt = Int32.Parse(digito);

                totalSumCharacters += digitoInt* multiplierRut;

                multiplierRut++;
                if(multiplierRut > 7)
                {
                    multiplierRut = 2;
                }
            }

            int paso1 = totalSumCharacters / 11;
            int paso2 = paso1 * 11;
            int paso3 = totalSumCharacters - paso2;
            int paso4 = 11 - paso3;

            string verificadorCalculado = paso4.ToString();
            if (verificadorCalculado == "10")
            {
                verificadorCalculado = "K";
            }
            else if (verificadorCalculado == "11")
            {
                verificadorCalculado = "0";
            }
            
            if (verificadorCalculado == verificadorInput) { return true; }
            else { return false; }
        }
    }
}

UAndes.ICC5103.202301/Controllers/FormulariosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Diagnostics;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using UAndes.ICC5103._202301.Models;

namespace UAndes.ICC5103._202301.Controllers
{
    public class FormulariosController : Controller
    {
        private InscripcionesBrDbGrupo06Entities db = new InscripcionesBrDbGrupo06Entities();
        private List<String> cnes_disponibles = new List<String>{ "Compraventa", "Regularización de Patrimonio" };

        // GET: Formularios
        public ActionResult Index()
        {
            return View(db.FormularioSet.ToList());
        }

        // GET: Formularios/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FormularioSet formularioSet = db.FormularioSet.Find(id);
            var adquirentes = db.AdquirenteSet.Where(adquiSet => adquiSet.FormularioSetNumeroAtencion == id);
            var enajenantes = db.EnajenanteSet.Where(enajenanteSet => enajenanteSet.FormularioSetNumeroAtencion == id);

            if (formularioSet == null)
            {
                return HttpNotFound();
            }

            ViewBag.adquirentes = adquirentes;
            ViewBag.enajenantes = enajenantes;
            return View(formularioSet);
        }

        // POST: Formularios/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        public ActionResult New(int? Id)
        {
            ViewBag.Comunas = db.Comunas;
            ViewBag.cnes_disponibles = cnes_disponibles;
            if (Id != null)
            {
                FormularioSet formularioSet = db.FormularioSet.Find(Id);

                ViewBag.adquirentes = db.AdquirenteSet.Where(adquirente => adquirente.FormularioSetNumeroAtencion == Id);
                ViewBag.enajenantes = db.EnajenanteSet.Where(enajenante => enajenante.FormularioSetNumeroAtencion == Id);
                ViewBag.FormularioSet = formularioSet;
                return View(formularioSet);
            }
            else
            {
                FormularioSet formularioSet = new FormularioSet();
                formularioSet.CNE = "";
                formularioSet.Comuna = "";
                formularioSet.Manzana = "";
                formularioSet.Predio = "";
                formularioSet.Fojas = "";
                formularioSet.FechaInscripcion = new DateTime(2023, 1, 1);
                formularioSet.NumeroInscripcion = 0;
                formularioSet.PorcentajeDisponible = new Decimal(100);

                if (ModelState.IsValid)
                {
                    db.FormularioSet.Add(formularioSet);
                    ViewBag.FormularioSet = formularioSet;
                    db.SaveChanges();
                }

                return View(formularioSet);
            }
        }

        // GET: Formularios/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FormularioSet formularioSet = db.FormularioSet.Find(id);
            var adquirentes = db.AdquirenteSet.Where(adquiSet => adquiSet.FormularioSetNumeroAtencion == id);
            var enajenantes = db.EnajenanteSet.Where(enajenanteSet => enajenanteSet.FormularioSetNumeroAtencion == id);

            if (formularioSet == null)
            {
                return HttpNotFound();
            }

            ViewBag.adquirentes = adquirentes;
            ViewBag.enajenantes = enajenantes;
            ViewBag.formularioSet = formularioSet;
            ViewBag.Comunas = db.Comunas;
            ViewBag.cnes_disponibles = cnes_disponibles;
            ViewBag.CNE = formularioSet.CNE;

            return View(formularioSet);
        }

        // POST: Formularios/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "NumeroAtencion,CNE,Comuna,Manzana,Predio,Fojas,FechaInscripcion,NumeroInscripcion")] FormularioSet formularioSet)
        {
            ViewBag.cnes_disponibles = cnes_disponibles;
            if (ModelState.IsValid)
            {
                var adquirentes = db.AdquirenteSet.Where(adquiSet => adquiSet.FormularioSetNumeroAtencion == formularioSet.NumeroAtencion);
                var enajenantes = db.EnajenanteSet.Where(enajenanteSet => enajenanteSet.FormularioSetNumeroAtencion == formularioSet.NumeroAtencion);

                ViewBag.adquirentes = adquirentes;
                ViewBag.enajenantes = enajenantes;
                ViewBag.formularioSet = formularioSet;
                ViewBag.Comunas = db.Comunas;
                ViewBag.CNE = formularioSet.CNE;

                db.Entry(formularioSet).State = EntityState.Modified;
                db.SaveChanges();
                //return RedirectToAction("Index");
            }
            return View(formularioSet);
        }

        // GET: Formularios/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FormularioSet formularioSet = db.FormularioSet.Find(id);
            if (formularioSet == null)
            {
                return HttpNotFound();
            }
            return View(formularioSet);
        }

        // POST: Formularios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int? id)
        {
            FormularioSet formularioSet = db.FormularioSet.Find(id);
            db.FormularioSet.Remove(formularioSet);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

UAndes.ICC5103.202301/Views/Formularios/Delete.cshtml
@model UAndes.ICC5103._202301.Models.FormularioSet

@{
    ViewBag.Title = "Delete";
}

<h2>Eliminar</h2>

<h3>Confirmar la eliminacion?</h3>
<div>
    <h4>Formulario</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            CNE
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CNE)
        </dd>

        <dt>
            Comuna
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Comuna)
        </dd>

        <dt>
            Manzana
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Manzana)
        </dd>

        <dt>
            Predio
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Predio)
        </dd>

        <dt>
            Fojas
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fojas)
        </dd>

        <dt>
            Fecha de Inscripcion
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaInscripcion)
        </dd>

        <dt>
            Numero de Inscripcion
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NumeroInscripcion)
        </dd>
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Eliminar" class="btn btn-default" /> |
            @Html.ActionLink("Volver al Listado", "Index")
        </div>
    }
</div>

UAndes.ICC5103.202301/Views/Formularios/Edit.cshtml
@model UAndes.ICC5103._202301.Models.FormularioSet

@{
    ViewBag.Title = "Edit";
}

<h2>Crear Formulario</h2>
<br></br>
<input type="hidden" id="formularioId" name="formId" value="@ViewBag.FormularioSet.NumeroAtencion" />
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>
            INSTRUCCIONES: Primero, rellenar datos del formulario y hacer click en "Guardar Formulario".
            Luego, ingresar enajenantes y adquirentes.
            Finalmente, hacer click en "Publicar Formulario".
        </h4>
        <br></br>
        <h4>Formulario</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.NumeroAtencion)

        <label>CNE</label>
        <div class="form-group">
            <div class="col-md-10">
                <select name="cne" id="cne-selector">
                    @foreach (var cne in ViewBag.cnes_disponibles)
                    {
                        <option value="@cne" @{ if (ViewBag.formularioSet.CNE == cne) { <text> selected</text> } }>@cne</option>
                    }
                </select>
            </div>
        </div>

        <label>Comuna</label>
        <div class="form-group">
            <div class="col-md-10">
                <select name="comuna">
                    @foreach (var comuna in ViewBag.Comunas)
                    {
                        <option value="@comuna.nombre" @{ if (ViewBag.formularioSet.Comuna == comuna.nombre) { <text> selected</text> } }>@comuna.nombre</option>
                    }
                </select>
            </div>
        </div>

        <label>Manzana</label>
        <div class="form-group">
            <div class="col-md-10">
                @Html.EditorFor(model => model.Manzana, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Manzana, "", new { @class = "text-danger" })
            </div>
        </div>

        <label>Predio</label>
        <div class="form-group">
            <div class="col-md-10">
                @Html.EditorFor(model => model.Predio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Predio, "", new { @class = "text-danger" })
            </div>
        </div>

        <label>Fojas</label>
        <div class="form-group">
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fojas, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fojas, "", new { @class = "text-danger" })
            </div>
        </div>

        <label>Fecha de Inscripcion</label>
        <div class="form-group">
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaInscripcion, new { htmlAttributes = new { @class = "form-control", @type = "date", @max = "3000-01-01", @onfocus = "this.max=new Date().toISOString().split('T')[0]" } })
                @Html.ValidationMessageFor(model => model.FechaInscripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <label>Numero de Inscripcion</label>
        <div class="form-group">
            <div class="col-md-10">
                @Html.EditorFor(model => model.NumeroInscripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NumeroInscripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar Formulario" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<div id="enajenantes">

    @if (ViewBag.CNE == "Compraventa")
    {
        <br></br>
        <h2>
            Enajenantes
        </h2>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">RUT</th>
                    <th scope="col">Porcentaje de Derechos</th>
                    <th scope="col">Derechos No Acreditados</th>
                </tr>
            </thead>
            <tbody>
                @if (ViewBag.enajenantes != null)
                {
                    foreach (var enajenante in ViewBag.enajenantes)
                    {
                        <tr>
                            <td>@enajenante.RUT</td>
                            <td>@enajenante.PorcentajeDerechos</td>
                            <td>@enajenante.DerechosNoAcreditados</td>
                        </tr>
                    }
                }
            </tbody>
        </table>


        using (Html.BeginForm("Create", "Enajenantes", FormMethod.Post))
        {
            @Html.AntiForgeryToken()

            <label for="rut">RUT:</label>
            <input type="text" id="rut" name="rut" />

            <label for="porcentajeDerechos">Porcentaje de Derechos:</label>
            <input type="text" id="porcentajeDerechos" name="porcentajeDerechos" value="0" />

            <label for="derechosNoAcreditados">Derechos No Acreditados:</label>
            <input type="checkbox" id="derechosNoAcreditados" name="derechosNoAcreditados" />

            @Html.HiddenFor(model => model.NumeroAtencion)

            <button type="submit">Agregar</button>
        }


    }
</div>
<br></br>

<h2>
    Adquirentes
</h2>
<table class="table">
    <thead>
        <tr>
            <th scope="col">RUT</th>
            <th scope="col">Porcentaje de Derechos</th>
            <th scope="col">Derechos No Acreditados</th>
        </tr>
    </thead>
    <tbody>
        @if (ViewBag.adquirentes != null)
        {
            foreach (var adquirente in ViewBag.adquirentes)
            {
                <tr>
                    <td>@adquirente.RUT</td>
                    <td>@adquirente.PorcentajeDerechos</td>
                    <td>@adquirente.DerechosNoAcreditados</td>
                </tr>
            }
        }
    </tbody>
</table>

@using (Html.BeginForm("Create", "Adquirentes", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <label for="rut">RUT:</label>
    <input type="text" id="rut" name="rut" />

    <label for="porcentajeDerechos">Porcentaje de Derechos:</label>
    <input type="text" id="porcentajeDerechos" name="porcentajeDerechos" value="0" />

    <label for="derechosNoAcreditados">Derechos No Acreditados:</label>
    <input type="checkbox" id="derechosNoAcreditados" name="derechosNoAcreditados" />

    @Html.HiddenFor(model => model.NumeroAtencion)

    <button type="submit">Agregar</button>
}
<br></br>

@using (Html.BeginForm("CreateFromAdquirentesController", "Multipropietarios", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    @Html.HiddenFor(model => model.NumeroAtencion)

    <button type="submit">Publicar Formulario</button>
}

<br></br>

<div>
    @Html.ActionLink("Volver al Listado", "Index")
</div>

UAndes.ICC5103.202301/Views/Formularios/New.cshtml
@model UAndes.ICC5103._202301.Models.FormularioSet

@{
    ViewBag.Title = "Create";
}

<input type="hidden" id="formularioId" name="formId" value="@ViewBag.FormularioSet.NumeroAtencion" />

<h2>Crear Formulario</h2>
<br></br>
@using (Html.BeginForm("Edit", "Formularios", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>
            INSTRUCCIONES: Primero, rellenar datos del formulario y hacer click en "Guardar Formulario".
            Luego, ingresar enajenantes y adquirentes.
            Finalmente, hacer click en "Publicar Formulario".
        </h4>
        <br></br>
        <h4>Formulario</h4>
        <hr />


        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        @Html.HiddenFor(model => model.NumeroAtencion)
        <label>CNE</label>
        <div class="form-group">
            <div class="col-md-10">
                <select name="cne" id="cne-selector">
                    @foreach (var cne in ViewBag.cnes_disponibles)
                    {
                        <option value="@cne" @{ if (ViewBag.formularioSet.CNE == cne) { <text> selected</text> } }>@cne</option>
                    }
                </select>
            </div>
        </div>

        <label>Comuna</label>
        <div class="form-group">

            <div class="col-md-10">
                <select name="Comuna">
                    @foreach (var comuna in ViewBag.Comunas)
                    {
                        <option value="@comuna.nombre">@comuna.nombre </option>
                    }
                </select>
            </div>
        </div>

        <label>Manzana</label>
        <div class="form-group d-flex">

            <div class="col-md-10">
                @Html.EditorFor(model => model.Manzana, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Manzana, "", new { @class = "text-danger" })
            </div>
        </div>

        <label>Predio</label>
        <div class="form-group d-flex">

            <div class="col-md-10">
                @Html.EditorFor(model => model.Predio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Predio, "", new { @class = "text-danger" })
            </div>
        </div>

        <label>Fojas</label>
        <div class="form-group d-flex">

            <div class="col-md-10">
                @Html.EditorFor(model => model.Fojas, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fojas, "", new { @class = "text-danger" })
            </div>
        </div>

        <label>Fecha de Inscripcion</label>
        <div class="form-group d-flex">
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaInscripcion, new { htmlAttributes = new { @class = "form-control", @type = "date", @max = "3000-01-01", @onfocus = "this.max=new Date().toISOString().split('T')[0]" } })
                @Html.ValidationMessageFor(model => model.FechaInscripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <label>Numero de Inscripcion</label>
        <div class="form-group d-flex">
            <div class="col-md-10">
                @Html.EditorFor(model => model.NumeroInscripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NumeroInscripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar Formulario" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<br></br>

<div id="second-form">
    <div id="enajenantes" class="hide">
        <h2>
            Enajenantes
        </h2>

        <table class="table">
            <thead>
                <tr>
                    <th scope="col">RUT</th>
                    <th scope="col">Porcentaje de Derechos</th>
                    <th scope="col">Derechos No Acreditados</th>
                </tr>
            </thead>
            <tbody>
                @if (ViewBag.enajenantes != null)
                {
                    foreach (var enajenante in ViewBag.enajenantes)
                    {
                        <tr>
                            <td>@enajenante.RUT</td>
                            <td>@enajenante.PorcentajeDerechos</td>
                            <td>@enajenante.DerechosNoAcreditados</td>
                        </tr>
                    }
                }
            </tbody>
        </table>

        @using (Html.BeginForm("Create", "Enajenantes", FormMethod.Post))
        {
            @Html.AntiForgeryToken()

            <label for="rut">RUT:</label>
            <input type="text" id="rut" name="rut" />

            <label for="porcentajeDerechos">Porcentaje de Derechos:</label>
            <input type="text" id="porcentajeDerechos" name="porcentajeDerechos" value="0" />

            <label for="derechosNoAcreditados">Derechos No Acreditados:</label>
            <input type="checkbox" id="derechosNoAcreditados" name="derechosNoAcreditados" />

            @Html.HiddenFor(model => model.NumeroAtencion)

            <button type="submit">Create</button>
        }
    </div>

    <br></br>
    <div id="adquirientes">
        <h2>
            Adquirentes
        </h2>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">RUT</th>
                    <th scope="col">Porcentaje de Derechos</th>
                    <th scope="col">Derechos No Acreditados</th>
                </tr>
            </thead>
            <tbody>
                @if (ViewBag.adquirentes != null)
                {
                    foreach (var adquirente in ViewBag.adquirentes)
                    {
                        <tr>
                            <td>@adquirente.RUT</td>
                            <td>@adquirente.PorcentajeDerechos</td>
                            <td>@adquirente.DerechosNoAcreditados</td>
                        </tr>
                    }
                }
            </tbody>
        </table>

        @using (Html.BeginForm("Create", "Adquirentes", FormMethod.Post))
        {
            @Html.AntiForgeryToken()

            <label for="rut">RUT:</label>
            <input type="text" id="rut" name="rut" />

            <label for="porcentajeDerechos">Porcentaje de Derechos:</label>
            <input type="text" id="porcentajeDerechos" name="porcentajeDerechos" value="0" />

            <label for="derechosNoAcreditados">Derechos No Acreditados:</label>
            <input type="checkbox" id="derechosNoAcreditados" name="derechosNoAcreditados" />

            @Html.HiddenFor(model => model.NumeroAtencion)

            <button type="submit">Create</button>
        }
    </div>
    <br></br>

    @using (Html.BeginForm("CreateFromAdquirentesController", "Multipropietarios", FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        @Html.HiddenFor(model => model.NumeroAtencion)

        <button type="submit">Publicar Formulario</button>
    }

    <br></br>
    <div>
        @Html.ActionLink("Volver al Listado", "Index")
    </div>